language: java

jdk:
  - oraclejdk8

#before_script:
#  - echo "MAVEN_OPTS='-Xmx2g -XX:MaxPermSize=512m'" > ~/.mavenrc

# Using && instead of two script steps to make Travis build fail faster, if "strict" compilation is not successful
script: mvn clean -Pstrict -pl '!benchmarks' compile test-compile -B && mvn test -B -Pparallel-test -Dmaven.fork.count=2

install: true

sudo: false

cache:
  directories:
      - $HOME/.m2

