language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2

install: true

matrix:
  include:
    - sudo: false
      script:
        # The script execution consists of 4 steps:
        # 1) Increase the jvm max heap size. Strict compilation in 2) requires more than 2 GB.
        # 2) Strict compilation using error-prone
        # 3) Reset the maven options. Parallel testing in 4) launches 2 processes, each requires 1 GB of memory. Increasing the maximum memory may cause OutOfMemory error because the instance of Travis has 4 GB of memory space.
        # 4) Parallel unit testing
        # Using && instead of independent script steps to make Travis build fail faster, if each step is not successful
        - echo "MAVEN_OPTS='-Xmx3000m'" > ~/.mavenrc && mvn clean -Pstrict -pl '!benchmarks' compile test-compile -B && rm ~/.mavenrc && mvn test -B -Pparallel-test -Dmaven.fork.count=2
    - sudo: required
      script:
        - $TRAVIS_BUILD_DIR/ci/travis_script_integration.sh


