language: java

jdk:
  - oraclejdk8

install: false

# Using && instead of two script steps to make Travis build fail faster, if "strict" compilation is not successful
script: echo "MAVEN_OPTS='-Xmx3000m'" > ~/.mavenrc && mvn clean -Pstrict -pl '!benchmarks' compile test-compile -B && rm ~/.mavenrc && mvn test -B -Pparallel-test -Dmaven.fork.count=2

sudo: false

cache:
  directories:
    - $HOME/.m2
