language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

matrix:
  include:
    - sudo: false
      script: echo "MAVEN_OPTS='-Xmx3000m'" > ~/.mavenrc && mvn clean -Pstrict -pl '!benchmarks' compile test-compile -B
    - sudo: false
      install: mvn install -q -ff -DskipTests -B
      script: mvn test -B -Pparallel-test -Dmaven.fork.count=2 -pl processing
    - sudo: false
      install: mvn install -q -ff -DskipTests -B
      script: mvn test -B -Pparallel-test -Dmaven.fork.count=2 -pl '!processing'
    - sudo: required
      services:
        - docker
      env:
        - DOCKER_IP=172.17.0.1
      install:
        # Only errors will be shown with the -q option. This is to avoid generating too many logs which make travis build failed.
        - mvn install -q -ff -DskipTests -B
      script:
        - $TRAVIS_BUILD_DIR/ci/travis_script_integration.sh
